export type BlogCopy = {
  title: string; description: string; featured: string; categories: string; popularTags: string;
  stayUpdated: string; subscribe: string; searchPlaceholder: string; searchLabel: string; clearSearch: string;
  article: string; articles: string; foundFor: string; noResults: string; previous: string; next: string;
  pagination: string; page: string; back: string; updated: string; minRead: string; tags: string; share: string;
  related: string; toc: string; previousArticle: string; nextArticle: string; postNavigation: string;
  inCategory: string; withTag: string; noCategory: string; noTag: string;
};

const copies: Record<string, BlogCopy> = {
  en: { title: 'Blog', description: 'PC gaming guides, hardware explainers, bottleneck tips, and optimization tutorials.', featured: 'Featured Articles', categories: 'Categories', popularTags: 'Popular Tags', stayUpdated: 'Stay Updated', subscribe: 'Subscribe via RSS', searchPlaceholder: 'Search by title, category, or tag…', searchLabel: 'Search blog posts', clearSearch: 'Clear search', article: 'article', articles: 'articles', foundFor: 'found for', noResults: 'No articles found. Try a different search term.', previous: 'Prev', next: 'Next', pagination: 'Blog pagination', page: 'Page', back: 'Back to Blog', updated: 'Updated', minRead: 'min read', tags: 'Tags', share: 'Share this article', related: 'Related Articles', toc: 'Table of Contents', previousArticle: 'Previous Article', nextArticle: 'Next Article', postNavigation: 'Post navigation', inCategory: 'in this category', withTag: 'with this tag', noCategory: 'No articles found in this category.', noTag: 'No articles found with this tag.' },
  it: { title: 'Blog', description: 'Guide sul gaming PC, spiegazioni hardware, consigli sui bottleneck e tutorial di ottimizzazione.', featured: 'Articoli in evidenza', categories: 'Categorie', popularTags: 'Tag popolari', stayUpdated: 'Resta aggiornato', subscribe: 'Iscriviti via RSS', searchPlaceholder: 'Cerca per titolo, categoria o tag…', searchLabel: 'Cerca nel blog', clearSearch: 'Cancella ricerca', article: 'articolo', articles: 'articoli', foundFor: 'trovati per', noResults: 'Nessun articolo trovato. Prova un altro termine.', previous: 'Prec.', next: 'Succ.', pagination: 'Paginazione del blog', page: 'Pagina', back: 'Torna al Blog', updated: 'Aggiornato', minRead: 'min di lettura', tags: 'Tag', share: 'Condividi questo articolo', related: 'Articoli correlati', toc: 'Indice', previousArticle: 'Articolo precedente', nextArticle: 'Articolo successivo', postNavigation: 'Navigazione articoli', inCategory: 'in questa categoria', withTag: 'con questo tag', noCategory: 'Nessun articolo in questa categoria.', noTag: 'Nessun articolo con questo tag.' },
  fr: { title: 'Blog', description: 'Guides PC gaming, explications matérielles, conseils bottleneck et tutoriels d’optimisation.', featured: 'Articles à la une', categories: 'Catégories', popularTags: 'Tags populaires', stayUpdated: 'Restez informé', subscribe: 'S’abonner via RSS', searchPlaceholder: 'Rechercher par titre, catégorie ou tag…', searchLabel: 'Rechercher dans le blog', clearSearch: 'Effacer la recherche', article: 'article', articles: 'articles', foundFor: 'trouvé(s) pour', noResults: 'Aucun article trouvé. Essayez un autre terme.', previous: 'Préc.', next: 'Suiv.', pagination: 'Pagination du blog', page: 'Page', back: 'Retour au Blog', updated: 'Mis à jour', minRead: 'min de lecture', tags: 'Tags', share: 'Partager cet article', related: 'Articles associés', toc: 'Sommaire', previousArticle: 'Article précédent', nextArticle: 'Article suivant', postNavigation: 'Navigation des articles', inCategory: 'dans cette catégorie', withTag: 'avec ce tag', noCategory: 'Aucun article dans cette catégorie.', noTag: 'Aucun article avec ce tag.' },
  de: { title: 'Blog', description: 'PC-Gaming-Ratgeber, Hardware-Erklärungen, Bottleneck-Tipps und Optimierungsanleitungen.', featured: 'Empfohlene Artikel', categories: 'Kategorien', popularTags: 'Beliebte Tags', stayUpdated: 'Aktuell bleiben', subscribe: 'Per RSS abonnieren', searchPlaceholder: 'Nach Titel, Kategorie oder Tag suchen…', searchLabel: 'Blog durchsuchen', clearSearch: 'Suche löschen', article: 'Artikel', articles: 'Artikel', foundFor: 'gefunden für', noResults: 'Keine Artikel gefunden. Versuchen Sie einen anderen Begriff.', previous: 'Zurück', next: 'Weiter', pagination: 'Blog-Seitennavigation', page: 'Seite', back: 'Zurück zum Blog', updated: 'Aktualisiert', minRead: 'Min. Lesezeit', tags: 'Tags', share: 'Artikel teilen', related: 'Ähnliche Artikel', toc: 'Inhaltsverzeichnis', previousArticle: 'Vorheriger Artikel', nextArticle: 'Nächster Artikel', postNavigation: 'Artikelnavigation', inCategory: 'in dieser Kategorie', withTag: 'mit diesem Tag', noCategory: 'Keine Artikel in dieser Kategorie.', noTag: 'Keine Artikel mit diesem Tag.' },
  es: { title: 'Blog', description: 'Guías de PC gaming, explicaciones de hardware, consejos de bottleneck y tutoriales de optimización.', featured: 'Artículos destacados', categories: 'Categorías', popularTags: 'Etiquetas populares', stayUpdated: 'Mantente al día', subscribe: 'Suscribirse por RSS', searchPlaceholder: 'Buscar por título, categoría o etiqueta…', searchLabel: 'Buscar en el blog', clearSearch: 'Borrar búsqueda', article: 'artículo', articles: 'artículos', foundFor: 'encontrado(s) para', noResults: 'No se encontraron artículos. Prueba otro término.', previous: 'Ant.', next: 'Sig.', pagination: 'Paginación del blog', page: 'Página', back: 'Volver al Blog', updated: 'Actualizado', minRead: 'min de lectura', tags: 'Etiquetas', share: 'Compartir este artículo', related: 'Artículos relacionados', toc: 'Contenido', previousArticle: 'Artículo anterior', nextArticle: 'Artículo siguiente', postNavigation: 'Navegación de artículos', inCategory: 'en esta categoría', withTag: 'con esta etiqueta', noCategory: 'No hay artículos en esta categoría.', noTag: 'No hay artículos con esta etiqueta.' },
};

export function getBlogCopy(locale: string): BlogCopy {
  return copies[locale] || copies.en;
}
