// Comprehensive Hardware Database (2017-2025)
// Excludes Apple Silicon as requested

export interface CPU {
  id: string;
  name: string;
  brand: 'Intel' | 'AMD';
  series: string;
  baseClock: number; // GHz
  boostClock: number; // GHz
  cores: number;
  threads: number;
  tdp: number; // Watts
  benchmarkScore: number; // Relative performance score
  releaseYear: number;
  launchPrice: number; // USD
  currentPrice: number; // USD
  tier: 'High-End' | 'Mid-Range' | 'Budget' | 'Entry-Level';
  category: 'Desktop' | 'Mobile' | 'Workstation' | 'Server';
  imageUrl: string;
  socket?: string;
  architecture: string;
  officialUrl?: string; // Official manufacturer product page URL
}

export interface GPU {
  id: string;
  name: string;
  brand: 'NVIDIA' | 'AMD';
  series: string;
  vram: number; // GB
  baseClock: number; // MHz
  boostClock: number; // MHz
  cudaCores?: number; // NVIDIA only
  streamProcessors?: number; // AMD only
  tdp: number; // Watts
  benchmarkScore: number; // Relative performance score
  releaseYear: number;
  launchPrice: number; // USD
  currentPrice: number; // USD
  tier: 'High-End' | 'Mid-Range' | 'Budget' | 'Entry-Level';
  category: 'Desktop' | 'Mobile' | 'Workstation';
  imageUrl: string;
  architecture: string;
  officialUrl?: string; // Official manufacturer product page URL
}

export interface Game {
  id: string;
  name: string;
  releaseYear: number;
  category: 'AAA' | 'Esports' | 'Indie' | 'Simulation' | 'Sandbox' | 'Survival';
  cpuDemand: 'Low' | 'Medium' | 'High' | 'Extreme';
  gpuDemand: 'Low' | 'Medium' | 'High' | 'Extreme';
  ramRequirement: number; // GB
  storageRequirement: number; // GB
  optimizations: string[]; // DLSS, FSR, etc.
}
// === CPU & GPU arrays (URLs fixed & validated fallbacks) ===

export const intelCPUs: CPU[] = [
  // 14th Gen Meteor Lake (2024-2025)
  {
    id: 'i9-14900KS',
    name: 'Intel Core i9-14900KS',
    brand: 'Intel',
    series: '14th Gen',
    baseClock: 3.2,
    boostClock: 6.0,
    cores: 24,
    threads: 32,
    tdp: 150,
    benchmarkScore: 98,
    releaseYear: 2024,
    launchPrice: 699,
    currentPrice: 649,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Raptor Lake Refresh',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i9-14900K',
    name: 'Intel Core i9-14900K',
    brand: 'Intel',
    series: '14th Gen',
    baseClock: 3.2,
    boostClock: 5.8,
    cores: 24,
    threads: 32,
    tdp: 125,
    benchmarkScore: 95,
    releaseYear: 2023,
    launchPrice: 589,
    currentPrice: 519,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Raptor Lake Refresh',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i7-14700K',
    name: 'Intel Core i7-14700K',
    brand: 'Intel',
    series: '14th Gen',
    baseClock: 3.4,
    boostClock: 5.6,
    cores: 20,
    threads: 28,
    tdp: 125,
    benchmarkScore: 88,
    releaseYear: 2023,
    launchPrice: 409,
    currentPrice: 369,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Raptor Lake Refresh',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i5-14600K',
    name: 'Intel Core i5-14600K',
    brand: 'Intel',
    series: '14th Gen',
    baseClock: 3.5,
    boostClock: 5.3,
    cores: 14,
    threads: 20,
    tdp: 125,
    benchmarkScore: 82,
    releaseYear: 2023,
    launchPrice: 319,
    currentPrice: 289,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Raptor Lake Refresh',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i9-13900KS',
    name: 'Intel Core i9-13900KS',
    brand: 'Intel',
    series: '13th Gen',
    baseClock: 3.0,
    boostClock: 6.0,
    cores: 24,
    threads: 32,
    tdp: 150,
    benchmarkScore: 94,
    releaseYear: 2023,
    launchPrice: 699,
    currentPrice: 589,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Raptor Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i9-13900K',
    name: 'Intel Core i9-13900K',
    brand: 'Intel',
    series: '13th Gen',
    baseClock: 3.0,
    boostClock: 5.8,
    cores: 24,
    threads: 32,
    tdp: 125,
    benchmarkScore: 92,
    releaseYear: 2022,
    launchPrice: 589,
    currentPrice: 479,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Raptor Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i7-13700K',
    name: 'Intel Core i7-13700K',
    brand: 'Intel',
    series: '13th Gen',
    baseClock: 3.4,
    boostClock: 5.4,
    cores: 16,
    threads: 24,
    tdp: 125,
    benchmarkScore: 85,
    releaseYear: 2022,
    launchPrice: 409,
    currentPrice: 329,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Raptor Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i5-13600K',
    name: 'Intel Core i5-13600K',
    brand: 'Intel',
    series: '13th Gen',
    baseClock: 3.5,
    boostClock: 5.1,
    cores: 14,
    threads: 20,
    tdp: 125,
    benchmarkScore: 79,
    releaseYear: 2022,
    launchPrice: 319,
    currentPrice: 259,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Raptor Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i9-12900KS',
    name: 'Intel Core i9-12900KS',
    brand: 'Intel',
    series: '12th Gen',
    baseClock: 3.4,
    boostClock: 5.5,
    cores: 16,
    threads: 24,
    tdp: 150,
    benchmarkScore: 89,
    releaseYear: 2022,
    launchPrice: 739,
    currentPrice: 449,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Alder Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i9-12900K',
    name: 'Intel Core i9-12900K',
    brand: 'Intel',
    series: '12th Gen',
    baseClock: 3.2,
    boostClock: 5.2,
    cores: 16,
    threads: 24,
    tdp: 125,
    benchmarkScore: 87,
    releaseYear: 2021,
    launchPrice: 589,
    currentPrice: 389,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Alder Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i7-12700K',
    name: 'Intel Core i7-12700K',
    brand: 'Intel',
    series: '12th Gen',
    baseClock: 3.6,
    boostClock: 5.0,
    cores: 12,
    threads: 20,
    tdp: 125,
    benchmarkScore: 81,
    releaseYear: 2021,
    launchPrice: 409,
    currentPrice: 289,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Alder Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i5-12600K',
    name: 'Intel Core i5-12600K',
    brand: 'Intel',
    series: '12th Gen',
    baseClock: 3.7,
    boostClock: 4.9,
    cores: 10,
    threads: 16,
    tdp: 125,
    benchmarkScore: 75,
    releaseYear: 2021,
    launchPrice: 289,
    currentPrice: 199,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1700',
    architecture: 'Alder Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i9-11900K',
    name: 'Intel Core i9-11900K',
    brand: 'Intel',
    series: '11th Gen',
    baseClock: 3.5,
    boostClock: 5.3,
    cores: 8,
    threads: 16,
    tdp: 125,
    benchmarkScore: 78,
    releaseYear: 2021,
    launchPrice: 539,
    currentPrice: 299,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1200',
    architecture: 'Rocket Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i7-11700K',
    name: 'Intel Core i7-11700K',
    brand: 'Intel',
    series: '11th Gen',
    baseClock: 3.6,
    boostClock: 5.0,
    cores: 8,
    threads: 16,
    tdp: 125,
    benchmarkScore: 74,
    releaseYear: 2021,
    launchPrice: 399,
    currentPrice: 249,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1200',
    architecture: 'Rocket Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i9-10900K',
    name: 'Intel Core i9-10900K',
    brand: 'Intel',
    series: '10th Gen',
    baseClock: 3.7,
    boostClock: 5.3,
    cores: 10,
    threads: 20,
    tdp: 125,
    benchmarkScore: 76,
    releaseYear: 2020,
    launchPrice: 488,
    currentPrice: 229,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1200',
    architecture: 'Comet Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i7-10700K',
    name: 'Intel Core i7-10700K',
    brand: 'Intel',
    series: '10th Gen',
    baseClock: 3.8,
    boostClock: 5.1,
    cores: 8,
    threads: 16,
    tdp: 125,
    benchmarkScore: 71,
    releaseYear: 2020,
    launchPrice: 374,
    currentPrice: 189,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1200',
    architecture: 'Comet Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i9-9900K',
    name: 'Intel Core i9-9900K',
    brand: 'Intel',
    series: '9th Gen',
    baseClock: 3.6,
    boostClock: 5.0,
    cores: 8,
    threads: 16,
    tdp: 95,
    benchmarkScore: 68,
    releaseYear: 2018,
    launchPrice: 488,
    currentPrice: 159,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1151',
    architecture: 'Coffee Lake Refresh',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i7-9700K',
    name: 'Intel Core i7-9700K',
    brand: 'Intel',
    series: '9th Gen',
    baseClock: 3.6,
    boostClock: 4.9,
    cores: 8,
    threads: 8,
    tdp: 95,
    benchmarkScore: 64,
    releaseYear: 2018,
    launchPrice: 374,
    currentPrice: 139,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1151',
    architecture: 'Coffee Lake Refresh',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i7-8700K',
    name: 'Intel Core i7-8700K',
    brand: 'Intel',
    series: '8th Gen',
    baseClock: 3.7,
    boostClock: 4.7,
    cores: 6,
    threads: 12,
    tdp: 95,
    benchmarkScore: 61,
    releaseYear: 2017,
    launchPrice: 359,
    currentPrice: 119,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1151',
    architecture: 'Coffee Lake',
    officialUrl: 'https://www.intel.com/'
  },
  {
    id: 'i7-7700K',
    name: 'Intel Core i7-7700K',
    brand: 'Intel',
    series: '7th Gen',
    baseClock: 4.2,
    boostClock: 4.5,
    cores: 4,
    threads: 8,
    tdp: 91,
    benchmarkScore: 52,
    releaseYear: 2017,
    launchPrice: 339,
    currentPrice: 89,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    socket: 'LGA1151',
    architecture: 'Kaby Lake',
    officialUrl: 'https://www.intel.com/'
  }
];

export const amdCPUs: CPU[] = [
  {
    id: 'ryzen-9-9950X',
    name: 'AMD Ryzen 9 9950X',
    brand: 'AMD',
    series: 'Ryzen 9000',
    baseClock: 4.3,
    boostClock: 5.7,
    cores: 16,
    threads: 32,
    tdp: 170,
    benchmarkScore: 96,
    releaseYear: 2024,
    launchPrice: 649,
    currentPrice: 599,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM5',
    architecture: 'Zen 5',
    officialUrl: 'https://www.amd.com/en/products/cpu/amd-ryzen-9-9950x'
  },
  {
    id: 'ryzen-9-9900X',
    name: 'AMD Ryzen 9 9900X',
    brand: 'AMD',
    series: 'Ryzen 9000',
    baseClock: 4.4,
    boostClock: 5.6,
    cores: 12,
    threads: 24,
    tdp: 120,
    benchmarkScore: 91,
    releaseYear: 2024,
    launchPrice: 499,
    currentPrice: 459,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM5',
    architecture: 'Zen 5',
    officialUrl: 'https://www.amd.com/en/products/cpu/amd-ryzen-9-9900x'
  },
  {
    id: 'ryzen-7-9700X',
    name: 'AMD Ryzen 7 9700X',
    brand: 'AMD',
    series: 'Ryzen 9000',
    baseClock: 3.8,
    boostClock: 5.5,
    cores: 8,
    threads: 16,
    tdp: 65,
    benchmarkScore: 86,
    releaseYear: 2024,
    launchPrice: 359,
    currentPrice: 329,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM5',
    architecture: 'Zen 5',
    officialUrl: 'https://www.amd.com/en/products/cpu/amd-ryzen-7-9700x'
  },
  {
    id: 'ryzen-5-9600X',
    name: 'AMD Ryzen 5 9600X',
    brand: 'AMD',
    series: 'Ryzen 9000',
    baseClock: 3.9,
    boostClock: 5.4,
    cores: 6,
    threads: 12,
    tdp: 65,
    benchmarkScore: 80,
    releaseYear: 2024,
    launchPrice: 279,
    currentPrice: 249,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM5',
    architecture: 'Zen 5',
    officialUrl: 'https://www.amd.com/en/products/cpu/amd-ryzen-5-9600x'
  },
  {
    id: 'ryzen-9-7950X',
    name: 'AMD Ryzen 9 7950X',
    brand: 'AMD',
    series: 'Ryzen 7000',
    baseClock: 4.5,
    boostClock: 5.7,
    cores: 16,
    threads: 32,
    tdp: 170,
    benchmarkScore: 93,
    releaseYear: 2022,
    launchPrice: 699,
    currentPrice: 489,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM5',
    architecture: 'Zen 4',
    officialUrl: 'https://www.amd.com/en/products/cpu/amd-ryzen-9-7950x'
  },
  {
    id: 'ryzen-9-7900X',
    name: 'AMD Ryzen 9 7900X',
    brand: 'AMD',
    series: 'Ryzen 7000',
    baseClock: 4.7,
    boostClock: 5.6,
    cores: 12,
    threads: 24,
    tdp: 170,
    benchmarkScore: 88,
    releaseYear: 2022,
    launchPrice: 549,
    currentPrice: 379,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM5',
    architecture: 'Zen 4',
    officialUrl: 'https://www.amd.com/en/products/cpu/amd-ryzen-9-7900x'
  },
  {
    id: 'ryzen-7-7700X',
    name: 'AMD Ryzen 7 7700X',
    brand: 'AMD',
    series: 'Ryzen 7000',
    baseClock: 4.5,
    boostClock: 5.4,
    cores: 8,
    threads: 16,
    tdp: 105,
    benchmarkScore: 83,
    releaseYear: 2022,
    launchPrice: 399,
    currentPrice: 279,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM5',
    architecture: 'Zen 4',
    officialUrl: 'https://www.amd.com/en/products/cpu/amd-ryzen-7-7700x'
  },
  {
    id: 'ryzen-5-7600X',
    name: 'AMD Ryzen 5 7600X',
    brand: 'AMD',
    series: 'Ryzen 7000',
    baseClock: 4.7,
    boostClock: 5.3,
    cores: 6,
    threads: 12,
    tdp: 105,
    benchmarkScore: 77,
    releaseYear: 2022,
    launchPrice: 299,
    currentPrice: 199,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM5',
    architecture: 'Zen 4',
    officialUrl: 'https://www.amd.com/en/products/cpu/amd-ryzen-5-7600x'
  },
  {
    id: 'ryzen-7-5800X3D',
    name: 'AMD Ryzen 7 5800X3D',
    brand: 'AMD',
    series: 'Ryzen 5000',
    baseClock: 3.4,
    boostClock: 4.5,
    cores: 8,
    threads: 16,
    tdp: 105,
    benchmarkScore: 84,
    releaseYear: 2022,
    launchPrice: 449,
    currentPrice: 289,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen 3+',
    officialUrl: 'https://www.amd.com/en/products/processors/desktops/ryzen/5000-series/amd-ryzen-7-5800x3d.html'
  },
  {
    id: 'ryzen-9-5950X',
    name: 'AMD Ryzen 9 5950X',
    brand: 'AMD',
    series: 'Ryzen 5000',
    baseClock: 3.4,
    boostClock: 4.9,
    cores: 16,
    threads: 32,
    tdp: 105,
    benchmarkScore: 89,
    releaseYear: 2020,
    launchPrice: 799,
    currentPrice: 399,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen 3',
    officialUrl: 'https://www.amd.com/en/products/processors/desktops/ryzen/5000-series/amd-ryzen-9-5950x.html'
  },
  {
    id: 'ryzen-9-5900X',
    name: 'AMD Ryzen 9 5900X',
    brand: 'AMD',
    series: 'Ryzen 5000',
    baseClock: 3.7,
    boostClock: 4.8,
    cores: 12,
    threads: 24,
    tdp: 105,
    benchmarkScore: 85,
    releaseYear: 2020,
    launchPrice: 549,
    currentPrice: 299,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen 3',
    officialUrl: 'https://www.amd.com/en/products/processors/desktops/ryzen/5000-series/amd-ryzen-9-5900x.html'
  },
  {
    id: 'ryzen-7-5800X',
    name: 'AMD Ryzen 7 5800X',
    brand: 'AMD',
    series: 'Ryzen 5000',
    baseClock: 3.8,
    boostClock: 4.7,
    cores: 8,
    threads: 16,
    tdp: 105,
    benchmarkScore: 80,
    releaseYear: 2020,
    launchPrice: 449,
    currentPrice: 219,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen 3',
    officialUrl: 'https://www.amd.com/en/products/processors/desktops/ryzen/5000-series/amd-ryzen-7-5800x.html'
  },
  {
    id: 'ryzen-5-5600X',
    name: 'AMD Ryzen 5 5600X',
    brand: 'AMD',
    series: 'Ryzen 5000',
    baseClock: 3.7,
    boostClock: 4.6,
    cores: 6,
    threads: 12,
    tdp: 65,
    benchmarkScore: 74,
    releaseYear: 2020,
    launchPrice: 299,
    currentPrice: 149,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen 3',
    officialUrl: 'https://www.amd.com/en/products/processors/desktops/ryzen/5000-series/amd-ryzen-5-5600x.html'
  },
  {
    id: 'ryzen-9-3950X',
    name: 'AMD Ryzen 9 3950X',
    brand: 'AMD',
    series: 'Ryzen 3000',
    baseClock: 3.5,
    boostClock: 4.7,
    cores: 16,
    threads: 32,
    tdp: 105,
    benchmarkScore: 82,
    releaseYear: 2019,
    launchPrice: 749,
    currentPrice: 289,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen 2',
    officialUrl: 'https://www.amd.com/en/products/specifications/processors.html'
  },
  {
    id: 'ryzen-9-3900X',
    name: 'AMD Ryzen 9 3900X',
    brand: 'AMD',
    series: 'Ryzen 3000',
    baseClock: 3.8,
    boostClock: 4.6,
    cores: 12,
    threads: 24,
    tdp: 105,
    benchmarkScore: 78,
    releaseYear: 2019,
    launchPrice: 499,
    currentPrice: 199,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen 2',
    officialUrl: 'https://www.amd.com/en/products/specifications/processors.html'
  },
  {
    id: 'ryzen-7-3700X',
    name: 'AMD Ryzen 7 3700X',
    brand: 'AMD',
    series: 'Ryzen 3000',
    baseClock: 3.6,
    boostClock: 4.4,
    cores: 8,
    threads: 16,
    tdp: 65,
    benchmarkScore: 72,
    releaseYear: 2019,
    launchPrice: 329,
    currentPrice: 159,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen 2',
    officialUrl: 'https://www.amd.com/en/products/specifications/processors.html'
  },
  {
    id: 'ryzen-5-3600X',
    name: 'AMD Ryzen 5 3600X',
    brand: 'AMD',
    series: 'Ryzen 3000',
    baseClock: 3.8,
    boostClock: 4.4,
    cores: 6,
    threads: 12,
    tdp: 95,
    benchmarkScore: 68,
    releaseYear: 2019,
    launchPrice: 249,
    currentPrice: 119,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen 2',
    officialUrl: 'https://www.amd.com/en/products/specifications/processors.html'
  },
  {
    id: 'ryzen-7-2700X',
    name: 'AMD Ryzen 7 2700X',
    brand: 'AMD',
    series: 'Ryzen 2000',
    baseClock: 3.7,
    boostClock: 4.3,
    cores: 8,
    threads: 16,
    tdp: 105,
    benchmarkScore: 64,
    releaseYear: 2018,
    launchPrice: 329,
    currentPrice: 99,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen+',
    officialUrl: 'https://www.amd.com/en/products/specifications/processors.html'
  },
  {
    id: 'ryzen-5-2600X',
    name: 'AMD Ryzen 5 2600X',
    brand: 'AMD',
    series: 'Ryzen 2000',
    baseClock: 3.6,
    boostClock: 4.2,
    cores: 6,
    threads: 12,
    tdp: 95,
    benchmarkScore: 58,
    releaseYear: 2018,
    launchPrice: 229,
    currentPrice: 79,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen+',
    officialUrl: 'https://www.amd.com/en/products/specifications/processors.html'
  },
  {
    id: 'ryzen-7-1700X',
    name: 'AMD Ryzen 7 1700X',
    brand: 'AMD',
    series: 'Ryzen 1000',
    baseClock: 3.4,
    boostClock: 3.8,
    cores: 8,
    threads: 16,
    tdp: 95,
    benchmarkScore: 55,
    releaseYear: 2017,
    launchPrice: 399,
    currentPrice: 69,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen',
    officialUrl: 'https://www.amd.com/en/products/specifications/processors.html'
  },
  {
    id: 'ryzen-5-1600X',
    name: 'AMD Ryzen 5 1600X',
    brand: 'AMD',
    series: 'Ryzen 1000',
    baseClock: 3.6,
    boostClock: 4.0,
    cores: 6,
    threads: 12,
    tdp: 95,
    benchmarkScore: 50,
    releaseYear: 2017,
    launchPrice: 249,
    currentPrice: 49,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg',
    socket: 'AM4',
    architecture: 'Zen',
    officialUrl: 'https://www.amd.com/en/products/specifications/processors.html'
  }
];

export const nvidiaGPUs: GPU[] = [
  {
    id: 'rtx-5090',
    name: 'NVIDIA GeForce RTX 5090',
    brand: 'NVIDIA',
    series: 'RTX 50',
    vram: 32,
    baseClock: 2230,
    boostClock: 2610,
    cudaCores: 21760,
    tdp: 575,
    benchmarkScore: 100,
    releaseYear: 2025,
    launchPrice: 1999,
    currentPrice: 1999,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Blackwell',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/' 
  },
  {
    id: 'rtx-5080',
    name: 'NVIDIA GeForce RTX 5080',
    brand: 'NVIDIA',
    series: 'RTX 50',
    vram: 16,
    baseClock: 2295,
    boostClock: 2620,
    cudaCores: 10752,
    tdp: 400,
    benchmarkScore: 92,
    releaseYear: 2025,
    launchPrice: 999,
    currentPrice: 999,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Blackwell',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5080/'
  },
  {
    id: 'rtx-5070-Ti',
    name: 'NVIDIA GeForce RTX 5070 Ti',
    brand: 'NVIDIA',
    series: 'RTX 50',
    vram: 16,
    baseClock: 2340,
    boostClock: 2570,
    cudaCores: 8960,
    tdp: 300,
    benchmarkScore: 85,
    releaseYear: 2025,
    launchPrice: 749,
    currentPrice: 749,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Blackwell',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/'
  },
  {
    id: 'rtx-5070',
    name: 'NVIDIA GeForce RTX 5070',
    brand: 'NVIDIA',
    series: 'RTX 50',
    vram: 12,
    baseClock: 2475,
    boostClock: 2640,
    cudaCores: 6144,
    tdp: 250,
    benchmarkScore: 78,
    releaseYear: 2025,
    launchPrice: 549,
    currentPrice: 549,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Blackwell',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/'
  },
  {
    id: 'rtx-4090',
    name: 'NVIDIA GeForce RTX 4090',
    brand: 'NVIDIA',
    series: 'RTX 40',
    vram: 24,
    baseClock: 2230,
    boostClock: 2520,
    cudaCores: 16384,
    tdp: 450,
    benchmarkScore: 95,
    releaseYear: 2022,
    launchPrice: 1599,
    currentPrice: 1399,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ada Lovelace',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4090/'
  },
  {
    id: 'rtx-4080-super',
    name: 'NVIDIA GeForce RTX 4080 SUPER',
    brand: 'NVIDIA',
    series: 'RTX 40',
    vram: 16,
    baseClock: 2295,
    boostClock: 2550,
    cudaCores: 10240,
    tdp: 320,
    benchmarkScore: 87,
    releaseYear: 2024,
    launchPrice: 999,
    currentPrice: 899,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ada Lovelace',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/'
  },
  {
    id: 'rtx-4080',
    name: 'NVIDIA GeForce RTX 4080',
    brand: 'NVIDIA',
    series: 'RTX 40',
    vram: 16,
    baseClock: 2205,
    boostClock: 2505,
    cudaCores: 9728,
    tdp: 320,
    benchmarkScore: 85,
    releaseYear: 2022,
    launchPrice: 1199,
    currentPrice: 849,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ada Lovelace',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4080/'
  },
  {
    id: 'rtx-4070-Ti-super',
    name: 'NVIDIA GeForce RTX 4070 Ti SUPER',
    brand: 'NVIDIA',
    series: 'RTX 40',
    vram: 16,
    baseClock: 2340,
    boostClock: 2610,
    cudaCores: 8448,
    tdp: 285,
    benchmarkScore: 82,
    releaseYear: 2024,
    launchPrice: 799,
    currentPrice: 749,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ada Lovelace',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/'
  },
  {
    id: 'rtx-4070-Ti',
    name: 'NVIDIA GeForce RTX 4070 Ti',
    brand: 'NVIDIA',
    series: 'RTX 40',
    vram: 12,
    baseClock: 2310,
    boostClock: 2610,
    cudaCores: 7680,
    tdp: 285,
    benchmarkScore: 79,
    releaseYear: 2023,
    launchPrice: 799,
    currentPrice: 649,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ada Lovelace',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/'
  },
  {
    id: 'rtx-4070-super',
    name: 'NVIDIA GeForce RTX 4070 SUPER',
    brand: 'NVIDIA',
    series: 'RTX 40',
    vram: 12,
    baseClock: 1980,
    boostClock: 2475,
    cudaCores: 7168,
    tdp: 220,
    benchmarkScore: 76,
    releaseYear: 2024,
    launchPrice: 599,
    currentPrice: 549,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ada Lovelace',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/'
  },
  {
    id: 'rtx-4070',
    name: 'NVIDIA GeForce RTX 4070',
    brand: 'NVIDIA',
    series: 'RTX 40',
    vram: 12,
    baseClock: 1920,
    boostClock: 2475,
    cudaCores: 5888,
    tdp: 200,
    benchmarkScore: 73,
    releaseYear: 2023,
    launchPrice: 599,
    currentPrice: 499,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ada Lovelace',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4070/'
  },
  {
    id: 'rtx-4060-Ti',
    name: 'NVIDIA GeForce RTX 4060 Ti',
    brand: 'NVIDIA',
    series: 'RTX 40',
    vram: 16,
    baseClock: 2310,
    boostClock: 2535,
    cudaCores: 4352,
    tdp: 165,
    benchmarkScore: 68,
    releaseYear: 2023,
    launchPrice: 499,
    currentPrice: 399,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ada Lovelace',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/'
  },
  {
    id: 'rtx-4060',
    name: 'NVIDIA GeForce RTX 4060',
    brand: 'NVIDIA',
    series: 'RTX 40',
    vram: 8,
    baseClock: 1830,
    boostClock: 2460,
    cudaCores: 3072,
    tdp: 115,
    benchmarkScore: 62,
    releaseYear: 2023,
    launchPrice: 299,
    currentPrice: 249,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ada Lovelace',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4060/'
  },
  {
    id: 'rtx-3090-Ti',
    name: 'NVIDIA GeForce RTX 3090 Ti',
    brand: 'NVIDIA',
    series: 'RTX 30',
    vram: 24,
    baseClock: 1560,
    boostClock: 1860,
    cudaCores: 10752,
    tdp: 450,
    benchmarkScore: 88,
    releaseYear: 2022,
    launchPrice: 1999,
    currentPrice: 899,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ampere',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/'
  },
  {
    id: 'rtx-3090',
    name: 'NVIDIA GeForce RTX 3090',
    brand: 'NVIDIA',
    series: 'RTX 30',
    vram: 24,
    baseClock: 1395,
    boostClock: 1695,
    cudaCores: 10496,
    tdp: 350,
    benchmarkScore: 86,
    releaseYear: 2020,
    launchPrice: 1499,
    currentPrice: 749,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ampere',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3090/'
  },
  {
    id: 'rtx-3080-Ti',
    name: 'NVIDIA GeForce RTX 3080 Ti',
    brand: 'NVIDIA',
    series: 'RTX 30',
    vram: 12,
    baseClock: 1365,
    boostClock: 1665,
    cudaCores: 10240,
    tdp: 350,
    benchmarkScore: 83,
    releaseYear: 2021,
    launchPrice: 1199,
    currentPrice: 599,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ampere',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/'
  },
  {
    id: 'rtx-3080',
    name: 'NVIDIA GeForce RTX 3080',
    brand: 'NVIDIA',
    series: 'RTX 30',
    vram: 10,
    baseClock: 1440,
    boostClock: 1710,
    cudaCores: 8704,
    tdp: 320,
    benchmarkScore: 80,
    releaseYear: 2020,
    launchPrice: 699,
    currentPrice: 449,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ampere',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3080/'
  },
  {
    id: 'rtx-3070-Ti',
    name: 'NVIDIA GeForce RTX 3070 Ti',
    brand: 'NVIDIA',
    series: 'RTX 30',
    vram: 8,
    baseClock: 1580,
    boostClock: 1770,
    cudaCores: 6144,
    tdp: 290,
    benchmarkScore: 75,
    releaseYear: 2021,
    launchPrice: 599,
    currentPrice: 349,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ampere',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/'
  },
  {
    id: 'rtx-3070',
    name: 'NVIDIA GeForce RTX 3070',
    brand: 'NVIDIA',
    series: 'RTX 30',
    vram: 8,
    baseClock: 1500,
    boostClock: 1725,
    cudaCores: 5888,
    tdp: 220,
    benchmarkScore: 72,
    releaseYear: 2020,
    launchPrice: 499,
    currentPrice: 299,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ampere',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3070/'
  },
  {
    id: 'rtx-3060-Ti',
    name: 'NVIDIA GeForce RTX 3060 Ti',
    brand: 'NVIDIA',
    series: 'RTX 30',
    vram: 8,
    baseClock: 1410,
    boostClock: 1665,
    cudaCores: 4864,
    tdp: 200,
    benchmarkScore: 68,
    releaseYear: 2020,
    launchPrice: 399,
    currentPrice: 249,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ampere',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3060-ti/'
  },
  {
    id: 'rtx-3060',
    name: 'NVIDIA GeForce RTX 3060',
    brand: 'NVIDIA',
    series: 'RTX 30',
    vram: 12,
    baseClock: 1320,
    boostClock: 1777,
    cudaCores: 3584,
    tdp: 170,
    benchmarkScore: 62,
    releaseYear: 2021,
    launchPrice: 329,
    currentPrice: 199,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Ampere',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/'
  },
  {
    id: 'rtx-2080-Ti',
    name: 'NVIDIA GeForce RTX 2080 Ti',
    brand: 'NVIDIA',
    series: 'RTX 20',
    vram: 11,
    baseClock: 1350,
    boostClock: 1545,
    cudaCores: 4352,
    tdp: 250,
    benchmarkScore: 70,
    releaseYear: 2018,
    launchPrice: 999,
    currentPrice: 299,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Turing',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'rtx-2080-super',
    name: 'NVIDIA GeForce RTX 2080 SUPER',
    brand: 'NVIDIA',
    series: 'RTX 20',
    vram: 8,
    baseClock: 1650,
    boostClock: 1815,
    cudaCores: 3072,
    tdp: 250,
    benchmarkScore: 67,
    releaseYear: 2019,
    launchPrice: 699,
    currentPrice: 249,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Turing',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'rtx-2070-super',
    name: 'NVIDIA GeForce RTX 2070 SUPER',
    brand: 'NVIDIA',
    series: 'RTX 20',
    vram: 8,
    baseClock: 1605,
    boostClock: 1770,
    cudaCores: 2560,
    tdp: 215,
    benchmarkScore: 64,
    releaseYear: 2019,
    launchPrice: 499,
    currentPrice: 199,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Turing',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'rtx-2060-super',
    name: 'NVIDIA GeForce RTX 2060 SUPER',
    brand: 'NVIDIA',
    series: 'RTX 20',
    vram: 8,
    baseClock: 1470,
    boostClock: 1650,
    cudaCores: 2176,
    tdp: 175,
    benchmarkScore: 58,
    releaseYear: 2019,
    launchPrice: 399,
    currentPrice: 149,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Turing',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'gtx-1660-Ti',
    name: 'NVIDIA GeForce GTX 1660 Ti',
    brand: 'NVIDIA',
    series: 'GTX 16',
    vram: 6,
    baseClock: 1500,
    boostClock: 1770,
    cudaCores: 1536,
    tdp: 120,
    benchmarkScore: 54,
    releaseYear: 2019,
    launchPrice: 279,
    currentPrice: 129,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Turing',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'gtx-1660-super',
    name: 'NVIDIA GeForce GTX 1660 SUPER',
    brand: 'NVIDIA',
    series: 'GTX 16',
    vram: 6,
    baseClock: 1530,
    boostClock: 1785,
    cudaCores: 1408,
    tdp: 125,
    benchmarkScore: 52,
    releaseYear: 2019,
    launchPrice: 229,
    currentPrice: 109,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Turing',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'gtx-1080-Ti',
    name: 'NVIDIA GeForce GTX 1080 Ti',
    brand: 'NVIDIA',
    series: 'GTX 10',
    vram: 11,
    baseClock: 1480,
    boostClock: 1582,
    cudaCores: 3584,
    tdp: 250,
    benchmarkScore: 63,
    releaseYear: 2017,
    launchPrice: 699,
    currentPrice: 199,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Pascal',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'gtx-1080',
    name: 'NVIDIA GeForce GTX 1080',
    brand: 'NVIDIA',
    series: 'GTX 10',
    vram: 8,
    baseClock: 1607,
    boostClock: 1733,
    cudaCores: 2560,
    tdp: 180,
    benchmarkScore: 58,
    releaseYear: 2016,
    launchPrice: 599,
    currentPrice: 149,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Pascal',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'gtx-1070-Ti',
    name: 'NVIDIA GeForce GTX 1070 Ti',
    brand: 'NVIDIA',
    series: 'GTX 10',
    vram: 8,
    baseClock: 1607,
    boostClock: 1683,
    cudaCores: 2432,
    tdp: 180,
    benchmarkScore: 55,
    releaseYear: 2017,
    launchPrice: 449,
    currentPrice: 129,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Pascal',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'gtx-1070',
    name: 'NVIDIA GeForce GTX 1070',
    brand: 'NVIDIA',
    series: 'GTX 10',
    vram: 8,
    baseClock: 1506,
    boostClock: 1683,
    cudaCores: 1920,
    tdp: 150,
    benchmarkScore: 52,
    releaseYear: 2016,
    launchPrice: 379,
    currentPrice: 109,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Pascal',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  },
  {
    id: 'gtx-1060-6gb',
    name: 'NVIDIA GeForce GTX 1060 6GB',
    brand: 'NVIDIA',
    series: 'GTX 10',
    vram: 6,
    baseClock: 1506,
    boostClock: 1708,
    cudaCores: 1280,
    tdp: 120,
    benchmarkScore: 45,
    releaseYear: 2016,
    launchPrice: 249,
    currentPrice: 79,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'Pascal',
    officialUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/'
  }
];

export const amdGPUs: GPU[] = [
  {
    id: 'rx-8800-XT',
    name: 'AMD Radeon RX 8800 XT',
    brand: 'AMD',
    series: 'RX 8000',
    vram: 16,
    baseClock: 2100,
    boostClock: 2400,
    streamProcessors: 4096,
    tdp: 250,
    benchmarkScore: 89,
    releaseYear: 2025,
    launchPrice: 649,
    currentPrice: 649,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 4',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon.html'
  },
  {
    id: 'rx-8700-XT',
    name: 'AMD Radeon RX 8700 XT',
    brand: 'AMD',
    series: 'RX 8000',
    vram: 12,
    baseClock: 2171,
    boostClock: 2544,
    streamProcessors: 3584,
    tdp: 245,
    benchmarkScore: 81,
    releaseYear: 2025,
    launchPrice: 449,
    currentPrice: 449,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 4',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon.html'
  },
  {
    id: 'rx-7900-XTX',
    name: 'AMD Radeon RX 7900 XTX',
    brand: 'AMD',
    series: 'RX 7000',
    vram: 24,
    baseClock: 1855,
    boostClock: 2500,
    streamProcessors: 6144,
    tdp: 355,
    benchmarkScore: 90,
    releaseYear: 2022,
    launchPrice: 999,
    currentPrice: 749,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 3',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/7000-series.html'
  },
  {
    id: 'rx-7900-XT',
    name: 'AMD Radeon RX 7900 XT',
    brand: 'AMD',
    series: 'RX 7000',
    vram: 20,
    baseClock: 1500,
    boostClock: 2400,
    streamProcessors: 5376,
    tdp: 300,
    benchmarkScore: 84,
    releaseYear: 2022,
    launchPrice: 899,
    currentPrice: 649,
    tier: 'High-End',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 3',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/7000-series.html'
  },
  {
    id: 'rx-7800-XT',
    name: 'AMD Radeon RX 7800 XT',
    brand: 'AMD',
    series: 'RX 7000',
    vram: 16,
    baseClock: 1295,
    boostClock: 2430,
    streamProcessors: 3840,
    tdp: 263,
    benchmarkScore: 77,
    releaseYear: 2023,
    launchPrice: 499,
    currentPrice: 429,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 3',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/7000-series.html'
  },
  {
    id: 'rx-7700-XT',
    name: 'AMD Radeon RX 7700 XT',
    brand: 'AMD',
    series: 'RX 7000',
    vram: 12,
    baseClock: 1700,
    boostClock: 2544,
    streamProcessors: 3456,
    tdp: 245,
    benchmarkScore: 72,
    releaseYear: 2023,
    launchPrice: 449,
    currentPrice: 379,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 3',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/7000-series.html'
  },
  {
    id: 'rx-7600-XT',
    name: 'AMD Radeon RX 7600 XT',
    brand: 'AMD',
    series: 'RX 7000',
    vram: 16,
    baseClock: 1755,
    boostClock: 2755,
    streamProcessors: 2048,
    tdp: 190,
    benchmarkScore: 65,
    releaseYear: 2024,
    launchPrice: 329,
    currentPrice: 299,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 3',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/7000-series.html'
  },
  {
    id: 'rx-7600',
    name: 'AMD Radeon RX 7600',
    brand: 'AMD',
    series: 'RX 7000',
    vram: 8,
    baseClock: 1720,
    boostClock: 2655,
    streamProcessors: 2048,
    tdp: 165,
    benchmarkScore: 60,
    releaseYear: 2023,
    launchPrice: 269,
    currentPrice: 229,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 3',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/7000-series.html'
  },
  {
    id: 'rx-6950-XT',
    name: 'AMD Radeon RX 6950 XT',
    brand: 'AMD',
    series: 'RX 6000',
    vram: 16,
    baseClock: 1860,
    boostClock: 2310,
    streamProcessors: 5120,
    tdp: 335,
    benchmarkScore: 82,
    releaseYear: 2022,
    launchPrice: 1099,
    currentPrice: 449,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 2',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/6000-series.html'
  },
  {
    id: 'rx-6900-XT',
    name: 'AMD Radeon RX 6900 XT',
    brand: 'AMD',
    series: 'RX 6000',
    vram: 16,
    baseClock: 1825,
    boostClock: 2250,
    streamProcessors: 5120,
    tdp: 300,
    benchmarkScore: 79,
    releaseYear: 2020,
    launchPrice: 999,
    currentPrice: 399,
    tier: 'Mid-Range',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 2',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/6000-series.html'
  },
  {
    id: 'rx-6800-XT',
    name: 'AMD Radeon RX 6800 XT',
    brand: 'AMD',
    series: 'RX 6000',
    vram: 16,
    baseClock: 1825,
    boostClock: 2250,
    streamProcessors: 4608,
    tdp: 300,
    benchmarkScore: 76,
    releaseYear: 2020,
    launchPrice: 649,
    currentPrice: 329,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 2',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/7000-series.html'
  },
  {
    id: 'rx-6800',
    name: 'AMD Radeon RX 6800',
    brand: 'AMD',
    series: 'RX 6000',
    vram: 16,
    baseClock: 1700,
    boostClock: 2105,
    streamProcessors: 3840,
    tdp: 250,
    benchmarkScore: 72,
    releaseYear: 2020,
    launchPrice: 579,
    currentPrice: 279,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 2',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/6000-series.html'
  },
  {
    id: 'rx-6700-XT',
    name: 'AMD Radeon RX 6700 XT',
    brand: 'AMD',
    series: 'RX 6000',
    vram: 12,
    baseClock: 2321,
    boostClock: 2581,
    streamProcessors: 2560,
    tdp: 230,
    benchmarkScore: 67,
    releaseYear: 2021,
    launchPrice: 479,
    currentPrice: 229,
    tier: 'Budget',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 2',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/6000-series.html'
  },
  {
    id: 'rx-6600-XT',
    name: 'AMD Radeon RX 6600 XT',
    brand: 'AMD',
    series: 'RX 6000',
    vram: 8,
    baseClock: 1968,
    boostClock: 2589,
    streamProcessors: 2048,
    tdp: 160,
    benchmarkScore: 61,
    releaseYear: 2021,
    launchPrice: 379,
    currentPrice: 179,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 2',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/6000-series.html'
  },
  {
    id: 'rx-6600',
    name: 'AMD Radeon RX 6600',
    brand: 'AMD',
    series: 'RX 6000',
    vram: 8,
    baseClock: 1626,
    boostClock: 2491,
    streamProcessors: 1792,
    tdp: 132,
    benchmarkScore: 57,
    releaseYear: 2021,
    launchPrice: 329,
    currentPrice: 149,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA 2',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/6000-series.html'
  },
  {
    id: 'rx-5700-XT',
    name: 'AMD Radeon RX 5700 XT',
    brand: 'AMD',
    series: 'RX 5000',
    vram: 8,
    baseClock: 1605,
    boostClock: 1905,
    streamProcessors: 2560,
    tdp: 225,
    benchmarkScore: 64,
    releaseYear: 2019,
    launchPrice: 399,
    currentPrice: 159,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon/7000-series.html'
  },
  {
    id: 'rx-5700',
    name: 'AMD Radeon RX 5700',
    brand: 'AMD',
    series: 'RX 5000',
    vram: 8,
    baseClock: 1465,
    boostClock: 1725,
    streamProcessors: 2304,
    tdp: 180,
    benchmarkScore: 59,
    releaseYear: 2019,
    launchPrice: 349,
    currentPrice: 129,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'RDNA',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon.html'
  },
  {
    id: 'rx-vega-64',
    name: 'AMD Radeon RX Vega 64',
    brand: 'AMD',
    series: 'RX Vega',
    vram: 8,
    baseClock: 1247,
    boostClock: 1546,
    streamProcessors: 4096,
    tdp: 295,
    benchmarkScore: 56,
    releaseYear: 2017,
    launchPrice: 499,
    currentPrice: 99,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'GCN 5.0',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon.html'
  },
  {
    id: 'rx-vega-56',
    name: 'AMD Radeon RX Vega 56',
    brand: 'AMD',
    series: 'RX Vega',
    vram: 8,
    baseClock: 1156,
    boostClock: 1471,
    streamProcessors: 3584,
    tdp: 210,
    benchmarkScore: 52,
    releaseYear: 2017,
    launchPrice: 399,
    currentPrice: 79,
    tier: 'Entry-Level',
    category: 'Desktop',
    imageUrl: 'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg',
    architecture: 'GCN 5.0',
    officialUrl: 'https://www.amd.com/en/products/graphics/desktops/radeon.html'
  }
];




// Latest Games (2020-2025)
export const modernGames: Game[] = [
  {
    id: 'gta-vi',
    name: 'Grand Theft Auto VI',
    releaseYear: 2025,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'Extreme',
    ramRequirement: 32,
    storageRequirement: 150,
    optimizations: ['DLSS 3', 'FSR 3']
  },
  {
    id: 'black-myth-wukong',
    name: 'Black Myth: Wukong',
    releaseYear: 2024,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 130,
    optimizations: ['DLSS 3', 'FSR 2']
  },
  {
    id: 'dragons-dogma-2',
    name: "Dragon's Dogma 2",
    releaseYear: 2024,
    category: 'AAA',
    cpuDemand: 'Extreme',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 70,
    optimizations: ['DLSS 3', 'FSR 2']
  },
  {
    id: 'helldivers-2',
    name: 'Helldivers 2',
    releaseYear: 2024,
    category: 'AAA',
    cpuDemand: 'Medium',
    gpuDemand: 'Medium',
    ramRequirement: 8,
    storageRequirement: 100,
    optimizations: ['DLSS 2', 'FSR 2']
  },
  {
    id: 'starfield',
    name: 'Starfield',
    releaseYear: 2023,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 125,
    optimizations: ['DLSS 3', 'FSR 2']
  },
  {
    id: 'baldurs-gate-3',
    name: "Baldur's Gate 3",
    releaseYear: 2023,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'Medium',
    ramRequirement: 16,
    storageRequirement: 150,
    optimizations: ['DLSS 2', 'FSR 2']
  },
  {
    id: 'cyberpunk-2077',
    name: 'Cyberpunk 2077',
    releaseYear: 2020,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'Extreme',
    ramRequirement: 16,
    storageRequirement: 70,
    optimizations: ['DLSS 3', 'FSR 2', 'Ray Tracing']
  },
  {
    id: 'elden-ring',
    name: 'Elden Ring',
    releaseYear: 2022,
    category: 'AAA',
    cpuDemand: 'Medium',
    gpuDemand: 'High',
    ramRequirement: 12,
    storageRequirement: 60,
    optimizations: ['FSR 2']
  },
  {
    id: 'counter-strike-2',
    name: 'Counter-Strike 2',
    releaseYear: 2023,
    category: 'Esports',
    cpuDemand: 'High',
    gpuDemand: 'Low',
    ramRequirement: 8,
    storageRequirement: 85,
    optimizations: ['NVIDIA Reflex']
  },
  {
    id: 'valorant',
    name: 'Valorant',
    releaseYear: 2020,
    category: 'Esports',
    cpuDemand: 'Medium',
    gpuDemand: 'Low',
    ramRequirement: 4,
    storageRequirement: 23,
    optimizations: ['NVIDIA Reflex']
  },
  {
    id: 'overwatch-2',
    name: 'Overwatch 2',
    releaseYear: 2022,
    category: 'Esports',
    cpuDemand: 'Medium',
    gpuDemand: 'Medium',
    ramRequirement: 6,
    storageRequirement: 50,
    optimizations: ['DLSS 3', 'NVIDIA Reflex']
  },
  {
    id: 'fortnite',
    name: 'Fortnite',
    releaseYear: 2017,
    category: 'Esports',
    cpuDemand: 'Medium',
    gpuDemand: 'Medium',
    ramRequirement: 8,
    storageRequirement: 26,
    optimizations: ['DLSS 3', 'FSR 2', 'NVIDIA Reflex']
  },
  {
    id: 'apex-legends',
    name: 'Apex Legends',
    releaseYear: 2019,
    category: 'Esports',
    cpuDemand: 'Medium',
    gpuDemand: 'Medium',
    ramRequirement: 8,
    storageRequirement: 75,
    optimizations: ['DLSS 2', 'NVIDIA Reflex']
  },
  {
    id: 'call-of-duty-warzone',
    name: 'Call of Duty: Warzone',
    releaseYear: 2020,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 175,
    optimizations: ['DLSS 3', 'FSR 2', 'NVIDIA Reflex']
  },
  {
    id: 'assassins-creed-mirage',
    name: "Assassin's Creed Mirage",
    releaseYear: 2023,
    category: 'AAA',
    cpuDemand: 'Medium',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 45,
    optimizations: ['DLSS 2', 'FSR 2']
  },
  {
    id: 'hogwarts-legacy',
    name: 'Hogwarts Legacy',
    releaseYear: 2023,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 85,
    optimizations: ['DLSS 3', 'FSR 2', 'Ray Tracing']
  },
  {
    id: 'the-witcher-3-nextgen',
    name: 'The Witcher 3: Wild Hunt (Next-Gen Update)',
    releaseYear: 2022,
    category: 'AAA',
    cpuDemand: 'Medium',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 80,
    optimizations: ['DLSS 3', 'FSR 2', 'Ray Tracing']
  },
  {
    id: 'red-dead-redemption-2',
    name: 'Red Dead Redemption 2',
    releaseYear: 2018,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'High',
    ramRequirement: 12,
    storageRequirement: 120,
    optimizations: ['DLSS 2', 'FSR 2']
  },
  {
    id: 'resident-evil-4-remake',
    name: 'Resident Evil 4 Remake',
    releaseYear: 2023,
    category: 'AAA',
    cpuDemand: 'Medium',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 60,
    optimizations: ['DLSS 2', 'FSR 2']
  },
  {
    id: 'spider-man-2',
    name: 'Marvelâ€™s Spider-Man 2',
    releaseYear: 2023,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 98,
    optimizations: ['DLSS 3', 'FSR 2', 'Ray Tracing']
  },
  {
    id: 'the-last-of-us-part-i',
    name: 'The Last of Us Part I (PC)',
    releaseYear: 2023,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 100,
    optimizations: ['DLSS 3', 'FSR 2', 'Ray Tracing']
  },
  {
    id: 'alan-wake-2',
    name: 'Alan Wake 2',
    releaseYear: 2023,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'Extreme',
    ramRequirement: 16,
    storageRequirement: 90,
    optimizations: ['DLSS 3.5', 'FSR 3', 'Path Tracing']
  },
  {
    id: 'forza-horizon-5',
    name: 'Forza Horizon 5',
    releaseYear: 2021,
    category: 'AAA',
    cpuDemand: 'Medium',
    gpuDemand: 'High',
    ramRequirement: 12,
    storageRequirement: 110,
    optimizations: ['DLSS 2', 'FSR 2']
  },
  {
    id: 'microsoft-flight-simulator',
    name: 'Microsoft Flight Simulator',
    releaseYear: 2020,
    category: 'Simulation',
    cpuDemand: 'Extreme',
    gpuDemand: 'High',
    ramRequirement: 32,
    storageRequirement: 150,
    optimizations: ['DLSS 3', 'FSR 2']
  },
  {
    id: 'rainbow-six-siege',
    name: 'Rainbow Six Siege',
    releaseYear: 2015,
    category: 'Esports',
    cpuDemand: 'Medium',
    gpuDemand: 'Medium',
    ramRequirement: 8,
    storageRequirement: 85,
    optimizations: ['DLSS 2', 'NVIDIA Reflex']
  },
  {
    id: 'pubg-battlegrounds',
    name: 'PUBG: Battlegrounds',
    releaseYear: 2017,
    category: 'Esports',
    cpuDemand: 'Medium',
    gpuDemand: 'Medium',
    ramRequirement: 8,
    storageRequirement: 40,
    optimizations: ['FSR 2', 'NVIDIA Reflex']
  },
  {
    id: 'league-of-legends',
    name: 'League of Legends',
    releaseYear: 2009,
    category: 'Esports',
    cpuDemand: 'Low',
    gpuDemand: 'Low',
    ramRequirement: 4,
    storageRequirement: 22,
    optimizations: ['NVIDIA Reflex']
  },
  {
    id: 'dota-2',
    name: 'Dota 2',
    releaseYear: 2013,
    category: 'Esports',
    cpuDemand: 'Medium',
    gpuDemand: 'Low',
    ramRequirement: 8,
    storageRequirement: 20,
    optimizations: ['FSR 2']
  },
  {
    id: 'minecraft-rtx',
    name: 'Minecraft (RTX Edition)',
    releaseYear: 2011,
    category: 'Sandbox',
    cpuDemand: 'Low',
    gpuDemand: 'Medium',
    ramRequirement: 8,
    storageRequirement: 2,
    optimizations: ['Ray Tracing', 'DLSS 2']
  },
  {
    id: 'genshin-impact',
    name: 'Genshin Impact',
    releaseYear: 2020,
    category: 'AAA',
    cpuDemand: 'Medium',
    gpuDemand: 'Medium',
    ramRequirement: 8,
    storageRequirement: 70,
    optimizations: ['FSR 2']
  },
  {
    id: 'palworld',
    name: 'Palworld',
    releaseYear: 2024,
    category: 'Survival',
    cpuDemand: 'Medium',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 40,
    optimizations: ['FSR 2']
  },
  {
    id: 'senua-saga-hellblade-ii',
    name: "Senua's Saga: Hellblade II",
    releaseYear: 2024,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'Extreme',
    ramRequirement: 32,
    storageRequirement: 100,
    optimizations: ['DLSS 3', 'FSR 3', 'Ray Tracing']
  },
  {
    id: 'fortnite-ue5-creative',
    name: 'Fortnite (UE5 Creative Mode)',
    releaseYear: 2023,
    category: 'Sandbox',
    cpuDemand: 'Medium',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 30,
    optimizations: ['DLSS 3', 'FSR 2']
  },
  {
    id: 'battlefield-2042',
    name: 'Battlefield 2042',
    releaseYear: 2021,
    category: 'AAA',
    cpuDemand: 'High',
    gpuDemand: 'High',
    ramRequirement: 16,
    storageRequirement: 100,
    optimizations: ['DLSS 3', 'FSR 2', 'Ray Tracing']
  }
];

// Combined hardware arrays
export const allCPUs = [...intelCPUs, ...amdCPUs].sort((a, b) => b.benchmarkScore - a.benchmarkScore);
export const allGPUs = [...nvidiaGPUs, ...amdGPUs].sort((a, b) => b.benchmarkScore - a.benchmarkScore);
export const allGames = modernGames.sort((a, b) => b.releaseYear - a.releaseYear);

// Helper functions
export function getCPUById(id: string): CPU | undefined {
  return allCPUs.find(cpu => cpu.id === id);
}

export function getGPUById(id: string): GPU | undefined {
  return allGPUs.find(gpu => gpu.id === id);
}

export function getGameById(id: string): Game | undefined {
  return allGames.find(game => game.id === id);
}

export function getCPUsByTier(tier: string): CPU[] {
  return allCPUs.filter(cpu => cpu.tier === tier);
}

export function getGPUsByTier(tier: string): GPU[] {
  return allGPUs.filter(gpu => gpu.tier === tier);
}

export function getGamesByCategory(category: string): Game[] {
  return allGames.filter(game => game.category === category);
}

// Performance calculation helpers
export function calculateBottleneckPercentage(cpu: CPU, gpu: GPU): number {
  const cpuScore = cpu.benchmarkScore;
  const gpuScore = gpu.benchmarkScore;
  
  if (cpuScore > gpuScore) {
    return Math.round(((cpuScore - gpuScore) / cpuScore) * 100);
  } else {
    return Math.round(((gpuScore - cpuScore) / gpuScore) * 100);
  }
}

export function getBottleneckType(cpu: CPU, gpu: GPU): 'CPU' | 'GPU' | 'Balanced' {
  const difference = Math.abs(cpu.benchmarkScore - gpu.benchmarkScore);
  
  if (difference <= 5) return 'Balanced';
  if (cpu.benchmarkScore < gpu.benchmarkScore) return 'CPU';
  return 'GPU';
}

export function estimateFPS(cpu: CPU, gpu: GPU, game: Game, resolution: string): number {
  const baseScore = Math.min(cpu.benchmarkScore, gpu.benchmarkScore);
  
  // Resolution multipliers
  const resolutionMultiplier = {
    '1080p': 1.0,
    '1440p': 0.7,
    '4K': 0.4
  }[resolution] || 1.0;
  
  // Game demand multipliers
  const demandMultiplier = {
    'Low': 1.2,
    'Medium': 1.0,
    'High': 0.8,
    'Extreme': 0.6
  }[game.gpuDemand] || 1.0;
  
  return Math.round(baseScore * resolutionMultiplier * demandMultiplier * 1.5);
}

export function calculatePSURequirement(cpu: CPU, gpu: GPU): number {
  const cpuPower = cpu.tdp;
  const gpuPower = gpu.tdp;
  const systemOverhead = 150; // Motherboard, RAM, storage, fans
  const safetyMargin = 1.2; // 20% headroom
  
  return Math.round((cpuPower + gpuPower + systemOverhead) * safetyMargin);
}
