import type { Locale } from '@/i18n-config';
import type { PsuTransientRisk } from '@/lib/psu-model';

export type PsuPhaseThreeCopy = {
  shareTitle: string;
  shareDescription: string;
  copyLink: string;
  copied: string;
  share: string;
  copyFailed: string;
  transientTitle: string;
  transientDescription: string;
  riskLabel: string;
  riskValues: Record<PsuTransientRisk, string>;
  riskDescriptions: Record<PsuTransientRisk, string>;
  combinedGpuPower: string;
  atxLabel: string;
  connectorLabel: string;
  dedicatedCables: string;
  yes: string;
  verify: string;
  standard: string;
  atxPreferred: string;
  atxVerify: string;
  vendorSpecified: string;
  nativePreferred: string;
  nativeVerify: string;
  referenceTitle: string;
  referenceDescription: string;
  intelSource: string;
  pciSigSource: string;
  safetyNotice: string;
};

const COPY: Record<Locale, PsuPhaseThreeCopy> = {
  en: {
    shareTitle: 'Save or share this PSU configuration', shareDescription: 'The link restores your CPU, GPU, peripherals, cooling, optional loads, and efficiency selection. Parameter URLs stay out of the sitemap and remain noindex.', copyLink: 'Copy result link', copied: 'Link copied', share: 'Share', copyFailed: 'Copy failed. Reopen the result and copy the browser address.',
    transientTitle: 'Transient load and connector readiness', transientDescription: 'This is a verification layer for short power excursions. It does not replace the exact GPU board-partner specification or a PSU review.', riskLabel: 'Transient risk signal', riskValues: { low: 'Lower', elevated: 'Elevated', high: 'High' }, riskDescriptions: { low: 'The combined GPU power is in a lower-risk planning band, but the GPU maker still decides the required PSU and connector.', elevated: 'A modern PSU with the right connector and enough 12 V capacity deserves closer verification for this GPU load.', high: 'Use the exact GPU and PSU documentation carefully. A second GPU or high combined GPU load makes connector and transient support especially important.' }, combinedGpuPower: 'Combined GPU power', atxLabel: 'PSU platform guidance', connectorLabel: 'GPU connector guidance', dedicatedCables: 'Dedicated GPU cables', yes: 'Yes — verify each cable run', verify: 'Verify exact model', standard: 'Standard PSU may be adequate; follow the vendor requirement', atxPreferred: 'Prefer an ATX 3.0/3.1 PSU and verify the vendor requirement', atxVerify: 'Verify ATX 3.0/3.1 transient support for this load', vendorSpecified: 'Use the exact GPU vendor/board-partner connector requirement', nativePreferred: 'Prefer a native 12VHPWR/12V-2x6 cable if the GPU requires it', nativeVerify: 'Verify native 12VHPWR/12V-2x6 support and cable fit', referenceTitle: 'Why this check exists', referenceDescription: 'Intel’s ATX 3.0 design guide defines PSU excursion test points, including higher short-duration levels for supplies with a high-current GPU connector. PCI-SIG defines the 12V-2x6 connector encoding. These references inform the checklist; they do not identify the connector for a specific GPU.', intelSource: 'Intel ATX 3.0 excursion reference', pciSigSource: 'PCI-SIG 12V-2x6 reference', safetyNotice: 'Planning estimate only: confirm the exact GPU minimum PSU wattage, connector type, native cable guidance, PSU protections, and independent model testing before purchase.'
  },
  it: {
    shareTitle: 'Salva o condividi questa configurazione PSU', shareDescription: 'Il link ripristina CPU, GPU, periferiche, raffreddamento, carichi opzionali e livello di efficienza. Gli URL con parametri restano fuori dalla sitemap e sono noindex.', copyLink: 'Copia link risultato', copied: 'Link copiato', share: 'Condividi', copyFailed: 'Copia non riuscita. Riapri il risultato e copia l’indirizzo del browser.',
    transientTitle: 'Carichi transitori e connettori', transientDescription: 'È un livello di verifica per i picchi brevi. Non sostituisce la specifica della scheda esatta o una recensione del PSU.', riskLabel: 'Segnale di rischio transitorio', riskValues: { low: 'Più basso', elevated: 'Elevato', high: 'Alto' }, riskDescriptions: { low: 'La potenza GPU combinata è in una fascia di pianificazione più bassa, ma il produttore decide comunque PSU e connettori.', elevated: 'Per questo carico GPU va verificato con attenzione un PSU moderno con connettore corretto e capacità 12 V sufficiente.', high: 'Controlla con cura la documentazione esatta di GPU e PSU. Una seconda GPU o un carico combinato alto rendono importanti connettori e supporto ai transitori.' }, combinedGpuPower: 'Potenza GPU combinata', atxLabel: 'Indicazione piattaforma PSU', connectorLabel: 'Indicazione connettore GPU', dedicatedCables: 'Cavi GPU dedicati', yes: 'Sì — verifica ogni cavo', verify: 'Verifica il modello esatto', standard: 'Un PSU standard può bastare; segui il requisito del produttore', atxPreferred: 'Preferisci un PSU ATX 3.0/3.1 e verifica il requisito del produttore', atxVerify: 'Verifica il supporto ai transitori ATX 3.0/3.1 per questo carico', vendorSpecified: 'Usa il requisito esatto del produttore/partner della GPU', nativePreferred: 'Preferisci un cavo nativo 12VHPWR/12V-2x6 se richiesto dalla GPU', nativeVerify: 'Verifica supporto nativo 12VHPWR/12V-2x6 e inserimento del cavo', referenceTitle: 'Perché questo controllo', referenceDescription: 'La guida ATX 3.0 di Intel definisce test per le escursioni PSU, inclusi livelli brevi più alti per alimentatori con connettore GPU ad alta corrente. PCI-SIG definisce il connettore 12V-2x6. Sono riferimenti per la checklist, non identificano il connettore di una GPU specifica.', intelSource: 'Riferimento Intel ATX 3.0', pciSigSource: 'Riferimento PCI-SIG 12V-2x6', safetyNotice: 'Stima di pianificazione: conferma wattaggio minimo, tipo di connettore, cavo nativo, protezioni PSU e test indipendenti del modello esatto prima dell’acquisto.'
  },
  fr: {
    shareTitle: 'Enregistrer ou partager cette configuration PSU', shareDescription: 'Le lien restaure CPU, GPU, périphériques, refroidissement, charges facultatives et efficacité. Les URL à paramètres restent hors sitemap et en noindex.', copyLink: 'Copier le lien du résultat', copied: 'Lien copié', share: 'Partager', copyFailed: 'Échec de la copie. Rouvrez le résultat et copiez l’adresse du navigateur.',
    transientTitle: 'Charges transitoires et connecteurs', transientDescription: 'Cette couche sert à vérifier les excursions brèves. Elle ne remplace pas la fiche de la carte exacte ni un test du PSU.', riskLabel: 'Signal de risque transitoire', riskValues: { low: 'Faible', elevated: 'Élevé', high: 'Fort' }, riskDescriptions: { low: 'La puissance GPU combinée est dans une plage de planification plus basse, mais le fabricant fixe toujours le PSU et les connecteurs requis.', elevated: 'Pour cette charge GPU, vérifiez attentivement un PSU moderne avec le bon connecteur et une capacité 12 V suffisante.', high: 'Vérifiez précisément les documents du GPU et du PSU. Un second GPU ou une forte charge combinée rendent les connecteurs et les transitoires particulièrement importants.' }, combinedGpuPower: 'Puissance GPU combinée', atxLabel: 'Conseil de plateforme PSU', connectorLabel: 'Conseil de connecteur GPU', dedicatedCables: 'Câbles GPU dédiés', yes: 'Oui — vérifiez chaque câble', verify: 'Vérifier le modèle exact', standard: 'Un PSU standard peut convenir; suivez la recommandation constructeur', atxPreferred: 'Préférez un PSU ATX 3.0/3.1 et vérifiez la recommandation constructeur', atxVerify: 'Vérifiez la prise en charge des transitoires ATX 3.0/3.1 pour cette charge', vendorSpecified: 'Suivez le connecteur exigé par le fabricant/partenaire de la carte exacte', nativePreferred: 'Préférez un câble natif 12VHPWR/12V-2x6 si le GPU l’exige', nativeVerify: 'Vérifiez le support natif 12VHPWR/12V-2x6 et l’insertion du câble', referenceTitle: 'Pourquoi ce contrôle existe', referenceDescription: 'Le guide ATX 3.0 d’Intel définit des points de test d’excursion PSU, avec des niveaux courts plus élevés pour les PSU dotés d’un connecteur GPU haute intensité. PCI-SIG définit le connecteur 12V-2x6. Ces références alimentent la checklist; elles n’identifient pas le connecteur d’un GPU précis.', intelSource: 'Référence Intel ATX 3.0', pciSigSource: 'Référence PCI-SIG 12V-2x6', safetyNotice: 'Estimation de planification : confirmez avant achat la puissance minimale GPU, le connecteur, le câble natif, les protections du PSU et les tests indépendants du modèle exact.'
  },
  de: {
    shareTitle: 'Diese PSU-Konfiguration speichern oder teilen', shareDescription: 'Der Link stellt CPU, GPU, Komponenten, Kühlung, optionale Lasten und Effizienz wieder her. Parameter-URLs bleiben aus der Sitemap und erhalten noindex.', copyLink: 'Ergebnislink kopieren', copied: 'Link kopiert', share: 'Teilen', copyFailed: 'Kopieren fehlgeschlagen. Ergebnis erneut öffnen und Browseradresse kopieren.',
    transientTitle: 'Transientenlast und Anschlussprüfung', transientDescription: 'Dies ist eine Prüfebene für kurze Leistungsspitzen. Sie ersetzt weder die Spezifikation der exakten Grafikkarte noch einen PSU-Test.', riskLabel: 'Signal für Transientenrisiko', riskValues: { low: 'Niedriger', elevated: 'Erhöht', high: 'Hoch' }, riskDescriptions: { low: 'Die kombinierte GPU-Leistung liegt in einem niedrigeren Planungsbereich; der Hersteller legt PSU- und Anschlussanforderungen dennoch fest.', elevated: 'Für diese GPU-Last sollte ein modernes Netzteil mit passendem Anschluss und ausreichender 12-V-Leistung genauer geprüft werden.', high: 'Prüfen Sie die exakten GPU- und PSU-Unterlagen sorgfältig. Eine zweite GPU oder hohe kombinierte GPU-Last macht Anschlüsse und Transienten besonders wichtig.' }, combinedGpuPower: 'Kombinierte GPU-Leistung', atxLabel: 'PSU-Plattformempfehlung', connectorLabel: 'GPU-Anschlussempfehlung', dedicatedCables: 'Separate GPU-Kabel', yes: 'Ja — jeden Kabelstrang prüfen', verify: 'Exaktes Modell prüfen', standard: 'Ein Standard-PSU kann ausreichen; Herstelleranforderung beachten', atxPreferred: 'ATX-3.0/3.1-PSU bevorzugen und Herstelleranforderung prüfen', atxVerify: 'ATX-3.0/3.1-Transientenunterstützung für diese Last prüfen', vendorSpecified: 'Exakte Anschlussanforderung des GPU-Herstellers/Boardpartners verwenden', nativePreferred: 'Natives 12VHPWR/12V-2x6-Kabel bevorzugen, falls von der GPU gefordert', nativeVerify: 'Natives 12VHPWR/12V-2x6 und korrekten Sitz prüfen', referenceTitle: 'Warum diese Prüfung existiert', referenceDescription: 'Intels ATX-3.0-Leitfaden definiert PSU-Excursion-Testpunkte, darunter höhere Kurzzeitwerte für Netzteile mit Hochstrom-GPU-Anschluss. PCI-SIG definiert den 12V-2x6-Anschluss. Die Referenzen informieren die Checkliste, bestimmen aber nicht den Anschluss einer bestimmten GPU.', intelSource: 'Intel-Referenz zu ATX 3.0', pciSigSource: 'PCI-SIG-Referenz zu 12V-2x6', safetyNotice: 'Planungsschätzung: Prüfen Sie vor dem Kauf die exakte GPU-Mindestleistung, Anschlusstyp, natives Kabel, PSU-Schutzschaltungen und unabhängige Tests des Modells.'
  },
  es: {
    shareTitle: 'Guarda o comparte esta configuración de PSU', shareDescription: 'El enlace restaura CPU, GPU, periféricos, refrigeración, cargas opcionales y eficiencia. Las URL con parámetros quedan fuera del sitemap y mantienen noindex.', copyLink: 'Copiar enlace del resultado', copied: 'Enlace copiado', share: 'Compartir', copyFailed: 'No se pudo copiar. Vuelve a abrir el resultado y copia la dirección del navegador.',
    transientTitle: 'Carga transitoria y conectores', transientDescription: 'Es una capa de verificación para picos breves. No sustituye la especificación de la tarjeta exacta ni una prueba de la PSU.', riskLabel: 'Señal de riesgo transitorio', riskValues: { low: 'Bajo', elevated: 'Elevado', high: 'Alto' }, riskDescriptions: { low: 'La potencia GPU combinada está en una banda de planificación menor, pero el fabricante sigue definiendo la PSU y los conectores necesarios.', elevated: 'Para esta carga GPU conviene verificar con más detalle una PSU moderna con el conector correcto y capacidad suficiente en 12 V.', high: 'Revisa con cuidado la documentación exacta de GPU y PSU. Una segunda GPU o una carga GPU combinada alta hacen especialmente importantes los conectores y el soporte transitorio.' }, combinedGpuPower: 'Potencia GPU combinada', atxLabel: 'Orientación de plataforma PSU', connectorLabel: 'Orientación de conector GPU', dedicatedCables: 'Cables GPU dedicados', yes: 'Sí — verifica cada cable', verify: 'Verifica el modelo exacto', standard: 'Una PSU estándar puede ser suficiente; sigue el requisito del fabricante', atxPreferred: 'Prefiere una PSU ATX 3.0/3.1 y verifica el requisito del fabricante', atxVerify: 'Verifica el soporte transitorio ATX 3.0/3.1 para esta carga', vendorSpecified: 'Usa el requisito exacto del fabricante/partner de la GPU', nativePreferred: 'Prefiere un cable nativo 12VHPWR/12V-2x6 si la GPU lo requiere', nativeVerify: 'Verifica soporte nativo 12VHPWR/12V-2x6 y el encaje del cable', referenceTitle: 'Por qué existe esta comprobación', referenceDescription: 'La guía ATX 3.0 de Intel define pruebas de excursión de PSU, con niveles breves más altos para fuentes con conector GPU de alta corriente. PCI-SIG define el conector 12V-2x6. Estas referencias informan la lista de comprobación, pero no identifican el conector de una GPU concreta.', intelSource: 'Referencia Intel ATX 3.0', pciSigSource: 'Referencia PCI-SIG 12V-2x6', safetyNotice: 'Estimación de planificación: confirma antes de comprar la potencia mínima de GPU, el conector, el cable nativo, las protecciones de la PSU y pruebas independientes del modelo exacto.'
  },
  ru: {
    shareTitle: 'Сохранить или поделиться этой конфигурацией PSU', shareDescription: 'Ссылка восстановит CPU, GPU, периферийные устройства, охлаждение, дополнительные нагрузки и эффективность. URL с параметрами не попадают в sitemap и остаются noindex.', copyLink: 'Копировать ссылку результата', copied: 'Ссылка скопирована', share: 'Поделиться', copyFailed: 'Не удалось скопировать. Снова откройте результат и скопируйте адрес браузера.',
    transientTitle: 'Переходные нагрузки и разъёмы', transientDescription: 'Это слой проверки кратковременных всплесков мощности. Он не заменяет документацию точной модели GPU и тесты PSU.', riskLabel: 'Сигнал переходного риска', riskValues: { low: 'Ниже', elevated: 'Повышенный', high: 'Высокий' }, riskDescriptions: { low: 'Суммарная мощность GPU находится в более низком плановом диапазоне, но производитель всё равно определяет требования к PSU и разъёмам.', elevated: 'Для такой нагрузки GPU внимательнее проверьте современный PSU с подходящим разъёмом и достаточной мощностью 12 В.', high: 'Тщательно проверьте документацию точных моделей GPU и PSU. Вторая GPU или высокая суммарная нагрузка делают разъёмы и поддержку переходных процессов особенно важными.' }, combinedGpuPower: 'Суммарная мощность GPU', atxLabel: 'Рекомендация по платформе PSU', connectorLabel: 'Рекомендация по разъёму GPU', dedicatedCables: 'Отдельные кабели GPU', yes: 'Да — проверьте каждый кабель', verify: 'Проверьте точную модель', standard: 'Обычный PSU может подойти; следуйте требованию производителя', atxPreferred: 'Предпочтителен PSU ATX 3.0/3.1; проверьте требование производителя', atxVerify: 'Проверьте поддержку переходных нагрузок ATX 3.0/3.1', vendorSpecified: 'Используйте точное требование производителя/партнёра платы GPU', nativePreferred: 'Предпочтителен штатный кабель 12VHPWR/12V-2x6, если он нужен GPU', nativeVerify: 'Проверьте штатную поддержку 12VHPWR/12V-2x6 и посадку кабеля', referenceTitle: 'Зачем нужна эта проверка', referenceDescription: 'Руководство Intel ATX 3.0 определяет тестовые уровни переходных нагрузок PSU, включая более высокие кратковременные уровни для блоков с силовым разъёмом GPU. PCI-SIG определяет разъём 12V-2x6. Эти источники помогают составить checklist, но не определяют разъём конкретной GPU.', intelSource: 'Справка Intel ATX 3.0', pciSigSource: 'Справка PCI-SIG 12V-2x6', safetyNotice: 'Плановая оценка: до покупки подтвердите минимальную мощность PSU для точной GPU, тип разъёма, штатный кабель, защиты PSU и независимые тесты модели.'
  },
};

export function getPsuPhaseThreeCopy(lang: Locale): PsuPhaseThreeCopy {
  return COPY[lang] ?? COPY.en;
}
