import { i18n } from '@/i18n-config';
import { getLocalizedPath } from '@/lib/path-translations';

/**
 * Constructs the canonical and language alternates for a given path.
 * This ensures proper 'hreflang' tags are generated by Next.js.
 * 
 * @param locale - The current locale (e.g., 'en', 'it').
 * @param path - The path relative to the domain root (e.g., '/about', '/fps-calculator'). 
 *               Should start with a slash if not empty.
 */
export function constructMetadataAlternates(locale: string, path: string = '') {
    const baseUrl = 'https://www.pcbuildcheck.com';

    // Ensure path is canonical (internal style) for lookup
    // The input 'path' here is expected to be the internal path (e.g. /about) because that's what we call from page.tsx files.

    // We want to generate alternates:
    // en: /en/about
    // it: /it/chi-siamo (via getLocalizedPath)

    const languages: Record<string, string> = {};

    // Generate URLs for all supported locales
    i18n.locales.forEach((l) => {
        // getLocalizedPath returns something like "/it/chi-siamo"
        const localPath = getLocalizedPath(l, path);
        languages[l] = `${baseUrl}${localPath}`;
    });

    // Send users whose language is not explicitly supported to English.
    // Keeping the fallback inside the same hreflang cluster also makes the
    // relationship between localized variants explicit to search engines.
    languages['x-default'] = `${baseUrl}${getLocalizedPath('en', path)}`;

    const currentLocalPath = getLocalizedPath(locale as any, path);

    return {
        canonical: `${baseUrl}${currentLocalPath}`,
        languages,
    };
}
